console.log(process.env.NODE_ENV);
/*

{
  ALLUSERSPROFILE: 'C:\\ProgramData',
  APPDATA: 'C:\\Users\\wqf123\\AppData\\Roaming',
  CHROME_CRASHPAD_PIPE_NAME: '\\\\.\\pipe\\crashpad_9020_WWOCWZPHVVSRDJBA',
  CommonProgramFiles: 'C:\\Program Files\\Common Files',
  'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
  CommonProgramW6432: 'C:\\Program Files\\Common Files',
  COMPUTERNAME: 'WANGQIFEI',
  ComSpec: 'C:\\WINDOWS\\system32\\cmd.exe',
  DataSpell: 'D:\\MyCodesoftware\\my_dataspell\\DataSpell 2022.1.1\\bin;',
  DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
  FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer',
  FPS_BROWSER_USER_PROFILE_STRING: 'Default',
  HOMEDRIVE: 'C:',
  HOMEPATH: '\\Users\\wqf123',
  KMP_DUPLICATE_LIB_OK: 'TRUE',
  LOCALAPPDATA: 'C:\\Users\\wqf123\\AppData\\Local',
  LOGONSERVER: '\\\\WANGQIFEI',
  LSHOST: 'wangqifei',
  MKL_SERIAL: 'YES',
  NUMBER_OF_PROCESSORS: '8',
  NVM_HOME: 'D:\\Apps\\my_nvm\\nvm',
  NVM_SYMLINK: 'C:\\Program Files\\nodejs',
  OneDrive: 'C:\\Users\\wqf123\\OneDrive',
  OneDriveConsumer: 'C:\\Users\\wqf123\\OneDrive',
  ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined',
  OS: 'Windows_NT',
  Path: 'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;D:\\Apps\\my_matlab\\matlab2019b\\runtime\\win64;D:\\Apps\\my_matlab\\matlab2019b\\bin;D:\\Apps\\my_matlab\\matlab2019b\\polyspace\\bin;D:\\mygit\\Git\\cmd;D:\\Apps\\xshell\\;C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\110\\Tools\\Binn\\;C:\\Program Files (x86)\\Common Files\\AspenTech Shared\\;D:\\Apps\\my_nvm\\nvm;C:\\Program Files\\nodejs;D:\\Apps\\xftp\\;D:\\Apps\\wechat_developer\\微信web开发者工具\\dll;D:\\mygit\\Git\\bin;C:\\Users\\wqf123\\AppData\\Local\\Microsoft\\WindowsApps;D:\\MyCodesoftware\\PyCharm Community Edition 2021.3.2\\bin;;D:\\MyCodesoftware\\mytree_graphviz\\Graphviz\\bin;D:\\MyCodesoftware\\my_dataspell\\DataSpell 2022.1.1\\bin;;D:\\MyCodesoftware\\my_vs_code\\Microsoft VS Code\\bin;node.exe;C:\\Users\\wqf123\\AppData\\Roaming\\npm;D:\\Apps\\my_nvm\\nvm;C:\\Program Files\\nodejs;C:\\Users\\wqf123\\Desktop\\notebook;C:\\Users\\wqf123\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;D:\\mygit\\Git\\bin;',
  PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL',
  PROCESSOR_ARCHITECTURE: 'AMD64',
  PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 140 Stepping 1, GenuineIntel',
  PROCESSOR_LEVEL: '6',
  PROCESSOR_REVISION: '8c01',
  ProgramData: 'C:\\ProgramData',
  ProgramFiles: 'C:\\Program Files',
  'ProgramFiles(x86)': 'C:\\Program Files (x86)',
  ProgramW6432: 'C:\\Program Files',
  PSModulePath: 'C:\\Users\\wqf123\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules',
  PUBLIC: 'C:\\Users\\Public',
  'PyCharm Community Edition': 'D:\\MyCodesoftware\\PyCharm Community Edition 2021.3.2\\bin;',
  RABBITMQ_CONFIG_FILE: 'aspenONE\\rabbitmq',
  SESSIONNAME: 'Console',
  SystemDrive: 'C:',
  SystemRoot: 'C:\\WINDOWS',
  TEMP: 'C:\\Users\\wqf123\\AppData\\Local\\Temp',
  TMP: 'C:\\Users\\wqf123\\AppData\\Local\\Temp',
  USERDOMAIN: 'wangqifei',
  USERDOMAIN_ROAMINGPROFILE: 'wangqifei',
  USERNAME: 'wqf123',
  USERPROFILE: 'C:\\Users\\wqf123',
  windir: 'C:\\WINDOWS',
  ZES_ENABLE_SYSMAN: '1',
  TERM_PROGRAM: 'vscode',
  TERM_PROGRAM_VERSION: '1.86.2',
  LANG: 'zh_CN.UTF-8',
  COLORTERM: 'truecolor',
  GIT_ASKPASS: 'd:\\MyCodesoftware\\my_vs_code\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh',
  VSCODE_GIT_ASKPASS_NODE: 'D:\\MyCodesoftware\\my_vs_code\\Microsoft VS Code\\Code.exe',
  VSCODE_GIT_ASKPASS_EXTRA_ARGS: '',
  VSCODE_GIT_ASKPASS_MAIN: 'd:\\MyCodesoftware\\my_vs_code\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js',
  VSCODE_GIT_IPC_HANDLE: '\\\\.\\pipe\\vscode-git-764bb2e1ec-sock',
  VSCODE_INJECTION: '1'
}


*/
